// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP1X-6ZfegDso5ra-WlHHkuDs4Tt1qimg',
    appId: '1:446094824789:android:0111e5fcdf939235164bdc',
    messagingSenderId: '446094824789',
    projectId: 'prime-296009',
    storageBucket: 'prime-296009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2US-AC9OUMSjPM24JYgg2HfA2CMk5mZM',
    appId: '1:446094824789:ios:9660a983bc64f7cd164bdc',
    messagingSenderId: '446094824789',
    projectId: 'prime-296009',
    storageBucket: 'prime-296009.firebasestorage.app',
    androidClientId: '446094824789-0mjtifv2ud1peiajaj01bb0prio08unc.apps.googleusercontent.com',
    iosClientId: '446094824789-cci30l8p8rm07ts8eoharpone8n48bjk.apps.googleusercontent.com',
    iosBundleId: 'com.jackbuild.prime.customer',
  );
}
